### ISSUE TITLE
Create individual ICS files for calendar entries

### ISSUE THREAD

**Issue by hd-script** [BernieO/calcardbackup#19]
I was able to export nextcloud calendar entries using this script, but it appears that it dumps everything into a single file. I am looking to import these entries to Radicale which needs separate entries. Is there a way this could be incorporated into the script?

Thanks in advance.

**Comment by BernieO** [comment]
Just to be sure: you want to export every single event to a single .ics file?

I never used radicale and thus don't have any experience with it. But I kind of can't believe that radicale is only capable of importing single events and not a complete calendar as .ics files. This would make radicale very unattractive for people who want to switch from another caldav server to radicale.
I had a quick look and stumpled across this:
https://github.com/Kozea/Radicale/issues/750#issuecomment-350297971
Could you try the curl command from that post with an ics file created from calcardbackup?

**Comment by hd-script** [comment]
Radicale uses separate ics file for each event, so I wanted to see if the export from Nextcloud could be split in similar manner. 

It did not occur to me to check their issues. Thanks, the curl command worked great. I was able to import all the calendars that I had.

Thanks again 🥇

**Comment by BernieO** [comment]
Thanks - glad to hear it worked.

It looks like the next major version of Radicale will include an upload dialog for complete calendars in the webinterface: https://github.com/Kozea/Radicale/pull/892#issuecomment-439133055

Back to *calcardbackup*: I think, exporting every single event of a calendar to single .ics files could be implemented. But I currently don‘t really see a use case here, since your problem has been solved. Also it would be another thing which needs to be maintained...

Closing this here for now. If anyone needs a feature like this: feel free to open this again.

**Comment by BernieO** [comment]
There were some use cases, where faulty database entries created problems in ownClouds/Nextclouds webinterface. To be able to export all events/cards as single files could also be a help for investigating problematic records in the database. The `calendardata` and `carddata` fields are stored as blobs in the database - having them as simple textfiles makes it easier to inspect them.

So, I had another thought about this and it will be implememted in the next release (v1.0), which will then be hosted on https://codeberg.org/BernieO/calcardbackup
